ajaxform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('student.urls')),
]

student/urls.py
from django.urls import path
from .views import home , save_data, newForm, home_value, home_value2

urlpatterns = [
    path('home/',home),
    path('save/',save_data, name='save'),
    path('form/',newForm),
    path('home/<int:value>/',home_value, name='homevalue'),
    path('home/<int:value>/<int:value2>',home_value2, name='homevalue'),

]

student/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
  name = models.CharField(max_length=55, blank=False)
  email = models.EmailField( blank=False)
  roll = models.IntegerField( blank=False)

  

student/forms.py
from .models import Student

from django import forms


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"


class Teacher(forms.Form):
    name1 = forms.CharField(max_length=11, min_length=4)

student/views.py
from django.shortcuts import render
from .forms import StudentForm, Teacher
from .models import Student
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

def home(request):
  std = Student.objects.all()
  t = Teacher()
  if request.method == "POST":
    form = StudentForm(request.POST)
    t = Teacher(request.POST)
    if form.is_valid():
      form.save()
      # print(f.cleaned_data['name'], f.cleaned_data['email'], f.cleaned_data['roll'])
    else:
      print("Form student not valid")
    if t.is_valid():
      print(t.cleaned_data['name'])
  else: 
    form = StudentForm()
  
  return render(request, "home.html", {'form': form, 'std': std, 'teacher': t})

@csrf_exempt
def save_data(request):
  if request.method == 'POST':
    form = StudentForm(request.POST)
    if form.is_valid():
      name = request.POST['name']
      email = request.POST['email']
      roll = request.POST['roll']
      print(name,email, roll)
      std = Student(name= name, email = email, roll=roll)
      std.save()
      return JsonResponse({'status':"Data saved successfully"})
    else:
      return JsonResponse({'status': "Failed"})
    
   
def newForm(request):
  if request.method == "POST":
    form = StudentForm(request.POST)
    if form.is_valid():
      print("Validated")
  else:
    form = StudentForm()
  return render(request, "frm.html", {'form': form})


def home_value(request, value):
  return HttpResponse(value*value)

def home_value2(request, value, value2):
  return HttpResponse(value2)

student/templates/ajax.html
<script>
$('#addstudent').click(function(){
console.log("Button Click add student");

let nm = $('#id_name').val();
let em = $('#id_email').val();
let rn = $('#id_roll').val();
console.log(nm, em, rn)

mydata = {name: nm, email: em, roll: rn }

$.ajax({
  url: "{% url 'save' %}",
  method: "POST", 
  data : mydata, 
  success: function(d){
    console.log(d)
  }

})

});

</script>

student/templates/frm.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>

  <form action="" method="POST" novalidate>
    {% csrf_token %}
    {{form}}

    <input type="submit" value="submit">
  </form>
</body>
</html>

student/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AJAX crud </title>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css"
    integrity="sha512-jnSuA4Ss2PkkikSOLtYs8BlYIeeIK1h99ty4YfvRPAlzr377vr3CXDb7sb7eEEBYjDtcYj+AjBH3FLv5uSJuXg=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
  <div class="container-fluid bg-info">
    <div class="row">
      <div class="col-md-6">
        <p class="display-1">Add Students.</p>
        <form action="" method="POST" novalidate >
          {% csrf_token %}
          {{form.as_p}}
          <input type="submit" value="Submit here" id="addstudent">
        </form>
      </div>

      <div class="col-md-6">
        <p class="display-1">List details Students.</p>

        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Email</th>
              <th scope="col">Roll No</th>
            </tr>
          </thead>
          <tbody>
            {% for s in std %}
            <tr>
              <td>{{s.id}}</td>
              <td>{{s.name}}</td>
              <td>{{s.email}}</td>
              <td>{{s.roll}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>


      </div>

    </div>
  </div>

  <div class="container">
    <div class="row">
      <form action="" method="POST" novalidate>
        {% csrf_token %}
        {{teacher}}

        <input type="submit" value="submit teacher">
      </form>
    </div>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
    integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.min.js"
    integrity="sha512-ykZ1QQr0Jy/4ZkvKuqWn4iF3lqPZyij9iRv6sGqLRdTPkY69YX6+7wvVGmsdBbiIfN/8OdsI7HABjvEok6ZopQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>

  {% include 'ajax.html' %}
</body>

</html>